Repository depromeet/SPURT-server, pull requests merged in 2025-02, with the labels that each got.

#20 feat: 공통 에러 처리 코드
  src/main/kotlin/com/ssak3/timeattack/global/advice/GlobalControllerAdvice.kt
  src/main/kotlin/com/ssak3/timeattack/global/exception/ApplicationException.kt
  src/main/kotlin/com/ssak3/timeattack/global/exception/ApplicationExceptionType.kt
  src/main/kotlin/com/ssak3/timeattack/global/response/ExceptionResponse.kt
Labels: Feature

#25 feat: ID 토큰 검증
  src/main/kotlin/com/ssak3/timeattack/global/exception/ApplicationExceptionType.kt
  src/main/kotlin/com/ssak3/timeattack/member/auth/client/OAuthTokenResponse.kt
  src/main/kotlin/com/ssak3/timeattack/member/auth/oidc/OIDCPayload.kt
  src/main/kotlin/com/ssak3/timeattack/member/auth/oidc/OIDCPublicKeyList.kt
  src/main/kotlin/com/ssak3/timeattack/member/auth/oidc/OIDCTokenVerification.kt
  src/test/kotlin/com/ssak3/timeattack/member/auth/oidc/OIDCTokenVerificationTest.kt
Labels: Feature

#28 OAuth 인증 정보로 회원 조회 로직 개발
  build.gradle.kts
  gradle.properties
  src/main/kotlin/com/ssak3/timeattack/common/config/QueryDslConfig.kt
  src/main/kotlin/com/ssak3/timeattack/member/infrastructure/MemberCustomRepository.kt
  src/main/kotlin/com/ssak3/timeattack/member/infrastructure/MemberCustomRepositoryImpl.kt
  src/main/kotlin/com/ssak3/timeattack/member/infrastructure/MemberRepository.kt
  src/main/resources/application-test.yml
  src/test/kotlin/com/ssak3/timeattack/member/infrastructure/MemberRepositoryTest.kt
Labels: Feature

#40 로그인 API 개발(Spring Security filter 설정 & JWT 토큰 발행)
  src/main/kotlin/com/ssak3/timeattack/TimeAttackApplication.kt
  src/main/kotlin/com/ssak3/timeattack/common/config/SecurityConfig.kt
  src/main/kotlin/com/ssak3/timeattack/common/security/JwtAuthenticationFilter.kt
  src/main/kotlin/com/ssak3/timeattack/common/security/JwtTokenDto.kt
  src/main/kotlin/com/ssak3/timeattack/common/security/JwtTokenProvider.kt
  src/main/kotlin/com/ssak3/timeattack/common/utils/JwtCookieUtil.kt
  src/main/kotlin/com/ssak3/timeattack/global/exception/ApplicationExceptionType.kt
  src/main/kotlin/com/ssak3/timeattack/member/auth/oidc/OIDCPublicKeyList.kt
  src/main/kotlin/com/ssak3/timeattack/member/auth/oidc/OIDCTokenVerification.kt
  src/main/kotlin/com/ssak3/timeattack/member/controller/AuthController.kt
  src/main/kotlin/com/ssak3/timeattack/member/controller/LoginRequest.kt
  src/main/kotlin/com/ssak3/timeattack/member/infrastructure/MemberRepository.kt
  src/main/kotlin/com/ssak3/timeattack/member/repository/MemberRepository.kt
  src/main/kotlin/com/ssak3/timeattack/member/repository/MemberRepositoryCustom.kt
  src/main/kotlin/com/ssak3/timeattack/member/repository/MemberRepositoryImpl.kt
  src/main/kotlin/com/ssak3/timeattack/member/service/AuthService.kt
  src/main/kotlin/com/ssak3/timeattack/member/service/MemberService.kt
  src/main/resources/application-dev.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/kotlin/com/ssak3/timeattack/member/auth/oidc/OIDCTokenVerificationTest.kt
  src/test/kotlin/com/ssak3/timeattack/member/repository/MemberRepositoryTest.kt
Labels: Feature

#42 FIX: ID token claims 변수명 수정(name -> nickname)
  src/main/kotlin/com/ssak3/timeattack/member/auth/oidc/OIDCTokenVerification.kt
  src/test/kotlin/com/ssak3/timeattack/member/auth/oidc/OIDCTokenVerificationTest.kt
Labels: Fix

#36 작업과 페르소나 도메인에 대해 도메인 클래스 및 엔티티 작성
  src/main/kotlin/com/ssak3/timeattack/persona/domain/Persona.kt
  src/main/kotlin/com/ssak3/timeattack/persona/domain/TaskKeywordsCombination.kt
  src/main/kotlin/com/ssak3/timeattack/persona/repository/entity/PersonaEntity.kt
  src/main/kotlin/com/ssak3/timeattack/task/domain/Task.kt
  src/main/kotlin/com/ssak3/timeattack/task/domain/TaskCategory.kt
  src/main/kotlin/com/ssak3/timeattack/task/domain/TaskMode.kt
  src/main/kotlin/com/ssak3/timeattack/task/domain/TaskStatus.kt
  src/main/kotlin/com/ssak3/timeattack/task/domain/TaskType.kt
  src/main/kotlin/com/ssak3/timeattack/task/repository/entity/TaskEntity.kt
  src/main/kotlin/com/ssak3/timeattack/task/repository/entity/TaskModeEntity.kt
  src/main/kotlin/com/ssak3/timeattack/task/repository/entity/TaskTypeEntity.kt
Labels: Feature

#44 토큰 유효 시간 오류 수정 및 Filter 동작 확인 테스트 API
  src/main/kotlin/com/ssak3/timeattack/common/security/JwtTokenProvider.kt
  src/main/kotlin/com/ssak3/timeattack/member/controller/AuthController.kt
Labels: Fix, Feature

#37 작업 작은행동 알림 저장 api, listener 생성
  src/main/kotlin/com/ssak3/timeattack/alarm/alarm.txt
  src/main/kotlin/com/ssak3/timeattack/notifications/controller/PushNotificationController.kt
  src/main/kotlin/com/ssak3/timeattack/notifications/controller/dto/PushNotificationCreateRequest.kt
  src/main/kotlin/com/ssak3/timeattack/notifications/domain/PushNotification.kt
  src/main/kotlin/com/ssak3/timeattack/notifications/repository/PushNotificationRepository.kt
  src/main/kotlin/com/ssak3/timeattack/notifications/repository/entity/PushNotificationEntity.kt
  src/main/kotlin/com/ssak3/timeattack/notifications/service/PushNotificationListener.kt
  src/main/kotlin/com/ssak3/timeattack/notifications/service/PushNotificationService.kt
Labels: Feature

#51 jwt 토큰 cookie -> header로 수정
  src/main/kotlin/com/ssak3/timeattack/common/security/JwtAuthenticationFilter.kt
  src/main/kotlin/com/ssak3/timeattack/member/controller/AuthController.kt
Labels: Refactor

#47 Swagger 설정
  build.gradle.kts
  src/main/kotlin/com/ssak3/timeattack/common/config/SwaggerConfig.kt
  src/main/kotlin/com/ssak3/timeattack/common/security/JwtAuthenticationFilter.kt
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: Feature

#48 Member 엔티티, 도메인 분리 및 디렉토리 수정
  src/main/kotlin/com/ssak3/timeattack/common/domain/BaseEntity.kt
  src/main/kotlin/com/ssak3/timeattack/member/domain/Member.kt
  src/main/kotlin/com/ssak3/timeattack/member/domain/OAuthProvider.kt
  src/main/kotlin/com/ssak3/timeattack/member/repository/MemberRepository.kt
  src/main/kotlin/com/ssak3/timeattack/member/repository/MemberRepositoryCustom.kt
  src/main/kotlin/com/ssak3/timeattack/member/repository/MemberRepositoryCustomImpl.kt
  src/main/kotlin/com/ssak3/timeattack/member/repository/MemberRepositoryImpl.kt
  src/main/kotlin/com/ssak3/timeattack/member/repository/entity/MemberEntity.kt
  src/main/kotlin/com/ssak3/timeattack/member/repository/entity/OAuthProviderInfo.kt
  src/main/kotlin/com/ssak3/timeattack/member/service/AuthService.kt
  src/main/kotlin/com/ssak3/timeattack/member/service/MemberService.kt
  src/main/kotlin/com/ssak3/timeattack/task/domain/Task.kt
  src/main/kotlin/com/ssak3/timeattack/task/repository/entity/TaskEntity.kt
  src/test/kotlin/com/ssak3/timeattack/member/repository/MemberRepositoryTest.kt
Labels: Refactor

#52 BaseEntity에 Audit 설정
  src/main/kotlin/com/ssak3/timeattack/TimeAttackApplication.kt
  src/main/kotlin/com/ssak3/timeattack/common/domain/BaseEntity.kt
  src/test/kotlin/com/ssak3/timeattack/member/repository/MemberRepositoryTest.kt
Labels: Refactor

#53 fcm 설정 및 푸시 알림 발송 API 생성(프론트 테스트용)
  build.gradle.kts
  src/main/kotlin/com/ssak3/timeattack/common/utils/Logger.kt
  src/main/kotlin/com/ssak3/timeattack/external/firebase/FirebaseCloudMessageService.kt
  src/main/kotlin/com/ssak3/timeattack/external/firebase/FirebaseConfig.kt
  src/main/kotlin/com/ssak3/timeattack/external/firebase/domain/DevicePlatform.kt
  src/main/kotlin/com/ssak3/timeattack/notifications/controller/PushNotificationController.kt
  src/main/kotlin/com/ssak3/timeattack/notifications/controller/dto/PushNotificationCreateRequest.kt
  src/main/kotlin/com/ssak3/timeattack/notifications/controller/dto/PushNotificationSendRequest.kt
  src/main/kotlin/com/ssak3/timeattack/notifications/domain/FcmMessage.kt
  src/main/kotlin/com/ssak3/timeattack/notifications/service/FcmPushNotificationService.kt
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: Feature

#56 refresh token으로 access/refresh token 재발급 API 개발
  src/main/kotlin/com/ssak3/timeattack/common/constant/Cache.kt
  src/main/kotlin/com/ssak3/timeattack/common/constant/CacheConst.kt
  src/main/kotlin/com/ssak3/timeattack/common/constant/SecurityConst.kt
  src/main/kotlin/com/ssak3/timeattack/common/security/JwtAuthenticationFilter.kt
  src/main/kotlin/com/ssak3/timeattack/common/security/refreshtoken/RefreshTokenEntity.kt
  src/main/kotlin/com/ssak3/timeattack/common/security/refreshtoken/RefreshTokenRedisRepository.kt
  src/main/kotlin/com/ssak3/timeattack/common/security/refreshtoken/RefreshTokenService.kt
  src/main/kotlin/com/ssak3/timeattack/common/utils/JwtCookieUtil.kt
  src/main/kotlin/com/ssak3/timeattack/global/exception/ApplicationExceptionType.kt
  src/main/kotlin/com/ssak3/timeattack/member/auth/client/KakaoFeignClient.kt
  src/main/kotlin/com/ssak3/timeattack/member/controller/AuthController.kt
  src/main/kotlin/com/ssak3/timeattack/member/controller/LoginRequest.kt
  src/main/kotlin/com/ssak3/timeattack/member/controller/RefreshRequest.kt
  src/main/kotlin/com/ssak3/timeattack/member/domain/Member.kt
  src/main/kotlin/com/ssak3/timeattack/member/service/AuthService.kt
  src/main/kotlin/com/ssak3/timeattack/member/service/MemberService.kt
Labels: Feature

#73 Task 상태 수정 API 개발 완료
  src/main/kotlin/com/ssak3/timeattack/global/exception/ApplicationExceptionType.kt
  src/main/kotlin/com/ssak3/timeattack/task/controller/TaskController.kt
  src/main/kotlin/com/ssak3/timeattack/task/controller/dto/TaskStatusRequest.kt
  src/main/kotlin/com/ssak3/timeattack/task/controller/dto/TaskStatusResponse.kt
  src/main/kotlin/com/ssak3/timeattack/task/domain/Task.kt
  src/main/kotlin/com/ssak3/timeattack/task/domain/TaskStatus.kt
  src/main/kotlin/com/ssak3/timeattack/task/service/TaskService.kt
  src/test/kotlin/com/ssak3/timeattack/fixture/Fixture.kt
  src/test/kotlin/com/ssak3/timeattack/task/domain/TaskStatusTest.kt
  src/test/kotlin/com/ssak3/timeattack/task/domain/TaskTest.kt
  src/test/kotlin/com/ssak3/timeattack/task/service/TaskServiceTest.kt
Labels: Feature

#75 fix: beforeStatus 삭제
  src/main/kotlin/com/ssak3/timeattack/task/controller/TaskController.kt
  src/main/kotlin/com/ssak3/timeattack/task/controller/dto/TaskStatusResponse.kt
Labels: Fix

#61 기기 정보 저장 이벤트 발행
  src/main/kotlin/com/ssak3/timeattack/common/domain/DeviceType.kt
  src/main/kotlin/com/ssak3/timeattack/member/controller/LoginRequest.kt
  src/main/kotlin/com/ssak3/timeattack/member/domain/Member.kt
  src/main/kotlin/com/ssak3/timeattack/member/repository/entity/OAuthProviderInfo.kt
  src/main/kotlin/com/ssak3/timeattack/member/service/AuthService.kt
  src/main/kotlin/com/ssak3/timeattack/member/service/events/DeviceRegisterEvent.kt
Labels: Feature

#85 이번 주 할 일 조회
  src/main/kotlin/com/ssak3/timeattack/notifications/repository/entity/PushNotificationEntity.kt
  src/main/kotlin/com/ssak3/timeattack/task/controller/TaskController.kt
  src/main/kotlin/com/ssak3/timeattack/task/controller/dto/TaskResponse.kt
  src/main/kotlin/com/ssak3/timeattack/task/repository/TaskRepository.kt
  src/main/kotlin/com/ssak3/timeattack/task/repository/TaskRepositoryCustom.kt
  src/main/kotlin/com/ssak3/timeattack/task/repository/TaskRepositoryCustomImpl.kt
  src/main/kotlin/com/ssak3/timeattack/task/service/TaskService.kt
  src/test/kotlin/com/ssak3/timeattack/fixture/Fixture.kt
  src/test/kotlin/com/ssak3/timeattack/task/service/TaskServiceTest.kt
Labels: Feature
